### PR TITLE
Add minimal elements module

### PR DESCRIPTION
**Pull request by mattwthompson**
## Description
This PR adds an extremely minimal "module" for elements. It provides only two dicts that return masses and symbols given an atomic number. The feature request is specified [here](https://github.com/openforcefield/openff-toolkit/issues/1178#issuecomment-1022644234).

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] Get an appropriate PR to the toolkit passing
  - [x] Find the source of OpenMM's data

### CODE REVIEW

**Comment by lilyminium** [comment]
Alternative suggestion: make an Element class. This allows the current API point `Atom.element` to continue existing. If you fudge around with `__new__` you can also ensure that the *same* element is returned every time, facilitating `is` comparisons.

I wrote the code below for a different project, but, well, if OpenFF wants to support it instead... ;) 

Masses are obtained from QCElemental here. `ImmutableModel` is a Pydantic subclass where changing attributes is forbidden, but obviously Pydantic is purely optional. Immutability has the advantage you don't want users messing with the attributes; without Pydantic, you could achieve the same by making `setattr` raise an error and assigning values via `__dict__`. The classes are defined in a separate module called elements.py so `elements.H` also returns the same object.

```python
from typing import ClassVar, Dict

from .base import ImmutableModel
from openff.units import unit


class Element(ImmutableModel):
    atomic_numbers: ClassVar[Dict[int, "Element"]] = {}
    symbols: ClassVar[Dict[str, "Element"]] = {}
    mass: unit.Quantity
    atomic_number: int
    symbol: str

    def __new__(cls, atomic_number: int = None, symbol: str = None, **kwargs):
        if atomic_number is not None and atomic_number in cls.atomic_numbers:
            element = cls.atomic_numbers[atomic_number]
            if symbol is not None and element.symbol != symbol:
                raise ValueError(
                    f"atomic_number={atomic_number} incompatible "
                    f"with symbol={symbol}. "
                    f"Expected element with symbol {element.symbol}"
                )
            return element
        
        if symbol is not None and symbol in cls.symbols:
            element = cls.symbols[symbol.capitalize()]
            if (atomic_number is not None
                    and element.atomic_number != atomic_number):
                raise ValueError(
                    f"symbol={symbol} incompatible "
                    f"with atomic_number={atomic_number}. "
                    f"Expected element with atomic_number "
                    f"{element.atomic_number}"
                )
            return element
        return super().__new__(cls)
    
    def __init__(self, atomic_number: int = None, symbol: str = None, **kwargs):
        if self not in self.atomic_numbers.values():
            super().__init__(
                atomic_number=atomic_number,
                symbol=symbol,
                **kwargs,
            )
            self.atomic_numbers[self.atomic_number] = self
            self.symbols[self.symbol] = self
```

Defining:
```python
X = Element(symbol="*",  atomic_number=0, mass=0 * unit.amu)
H = Element(symbol="H", atomic_number=1, mass=1.00782503223 * unit.amu)
He = Element(symbol="He", atomic_number=2, mass=4.00260325413 * unit.amu)
Li = Element(symbol="Li", atomic_number=3, mass=7.0160034366 * unit.amu)
Be = Element(symbol="Be", atomic_number=4, mass=9.012183065 * unit.amu)
B = Element(symbol="B", atomic_number=5, mass=11.00930536 * unit.amu)
C = Element(symbol="C", atomic_number=6, mass=12.0 * unit.amu)
N = Element(symbol="N", atomic_number=7, mass=14.00307400443 * unit.amu)
O = Element(symbol="O", atomic_number=8, mass=15.99491461957 * unit.amu)
F = Element(symbol="F", atomic_number=9, mass=18.99840316273 * unit.amu)
Ne = Element(symbol="Ne", atomic_number=10, mass=19.9924401762 * unit.amu)
Na = Element(symbol="Na", atomic_number=11, mass=22.989769282 * unit.amu)
Mg = Element(symbol="Mg", atomic_number=12, mass=23.985041697 * unit.amu)
Al = Element(symbol="Al", atomic_number=13, mass=26.98153853 * unit.amu)
Si = Element(symbol="Si", atomic_number=14, mass=27.97692653465 * unit.amu)
P = Element(symbol="P", atomic_number=15, mass=30.97376199842 * unit.amu)
S = Element(symbol="S", atomic_number=16, mass=31.9720711744 * unit.amu)
Cl = Element(symbol="Cl", atomic_number=17, mass=34.968852682 * unit.amu)
Ar = Element(symbol="Ar", atomic_number=18, mass=39.9623831237 * unit.amu)
K = Element(symbol="K", atomic_number=19, mass=38.9637064864 * unit.amu)
Ca = Element(symbol="Ca", atomic_number=20, mass=39.962590863 * unit.amu)
Sc = Element(symbol="Sc", atomic_number=21, mass=44.95590828 * unit.amu)
Ti = Element(symbol="Ti", atomic_number=22, mass=47.94794198 * unit.amu)
V = Element(symbol="V", atomic_number=23, mass=50.94395704 * unit.amu)
Cr = Element(symbol="Cr", atomic_number=24, mass=51.94050623 * unit.amu)
Mn = Element(symbol="Mn", atomic_number=25, mass=54.93804391 * unit.amu)
Fe = Element(symbol="Fe", atomic_number=26, mass=55.93493633 * unit.amu)
Co = Element(symbol="Co", atomic_number=27, mass=58.93319429 * unit.amu)
Ni = Element(symbol="Ni", atomic_number=28, mass=57.93534241 * unit.amu)
Cu = Element(symbol="Cu", atomic_number=29, mass=62.92959772 * unit.amu)
Zn = Element(symbol="Zn", atomic_number=30, mass=63.92914201 * unit.amu)
Ga = Element(symbol="Ga", atomic_number=31, mass=68.9255735 * unit.amu)
Ge = Element(symbol="Ge", atomic_number=32, mass=73.921177761 * unit.amu)
As = Element(symbol="As", atomic_number=33, mass=74.92159457 * unit.amu)
Se = Element(symbol="Se", atomic_number=34, mass=79.9165218 * unit.amu)
Br = Element(symbol="Br", atomic_number=35, mass=78.9183376 * unit.amu)
Kr = Element(symbol="Kr", atomic_number=36, mass=83.9114977282 * unit.amu)
Rb = Element(symbol="Rb", atomic_number=37, mass=84.9117897379 * unit.amu)
Sr = Element(symbol="Sr", atomic_number=38, mass=87.9056125 * unit.amu)
Y = Element(symbol="Y", atomic_number=39, mass=88.9058403 * unit.amu)
Zr = Element(symbol="Zr", atomic_number=40, mass=89.9046977 * unit.amu)
Nb = Element(symbol="Nb", atomic_number=41, mass=92.906373 * unit.amu)
Mo = Element(symbol="Mo", atomic_number=42, mass=97.90540482 * unit.amu)
Tc = Element(symbol="Tc", atomic_number=43, mass=97.9072124 * unit.amu)
Ru = Element(symbol="Ru", atomic_number=44, mass=101.9043441 * unit.amu)
Rh = Element(symbol="Rh", atomic_number=45, mass=102.905498 * unit.amu)
Pd = Element(symbol="Pd", atomic_number=46, mass=105.9034804 * unit.amu)
Ag = Element(symbol="Ag", atomic_number=47, mass=106.9050916 * unit.amu)
Cd = Element(symbol="Cd", atomic_number=48, mass=113.90336509 * unit.amu)
In = Element(symbol="In", atomic_number=49, mass=114.903878776 * unit.amu)
Sn = Element(symbol="Sn", atomic_number=50, mass=119.90220163 * unit.amu)
Sb = Element(symbol="Sb", atomic_number=51, mass=120.903812 * unit.amu)
Te = Element(symbol="Te", atomic_number=52, mass=129.906222748 * unit.amu)
I = Element(symbol="I", atomic_number=53, mass=126.9044719 * unit.amu)
Xe = Element(symbol="Xe", atomic_number=54, mass=131.9041550856 * unit.amu)
Cs = Element(symbol="Cs", atomic_number=55, mass=132.905451961 * unit.amu)
Ba = Element(symbol="Ba", atomic_number=56, mass=137.905247 * unit.amu)
La = Element(symbol="La", atomic_number=57, mass=138.9063563 * unit.amu)
Ce = Element(symbol="Ce", atomic_number=58, mass=139.9054431 * unit.amu)
Pr = Element(symbol="Pr", atomic_number=59, mass=140.9076576 * unit.amu)
Nd = Element(symbol="Nd", atomic_number=60, mass=141.907729 * unit.amu)
Pm = Element(symbol="Pm", atomic_number=61, mass=144.9127559 * unit.amu)
Sm = Element(symbol="Sm", atomic_number=62, mass=151.9197397 * unit.amu)
Eu = Element(symbol="Eu", atomic_number=63, mass=152.921238 * unit.amu)
Gd = Element(symbol="Gd", atomic_number=64, mass=157.9241123 * unit.amu)
Tb = Element(symbol="Tb", atomic_number=65, mass=158.9253547 * unit.amu)
Dy = Element(symbol="Dy", atomic_number=66, mass=163.9291819 * unit.amu)
Ho = Element(symbol="Ho", atomic_number=67, mass=164.9303288 * unit.amu)
Er = Element(symbol="Er", atomic_number=68, mass=165.9302995 * unit.amu)
Tm = Element(symbol="Tm", atomic_number=69, mass=168.9342179 * unit.amu)
Yb = Element(symbol="Yb", atomic_number=70, mass=173.9388664 * unit.amu)
Lu = Element(symbol="Lu", atomic_number=71, mass=174.9407752 * unit.amu)
Hf = Element(symbol="Hf", atomic_number=72, mass=179.946557 * unit.amu)
Ta = Element(symbol="Ta", atomic_number=73, mass=180.9479958 * unit.amu)
W = Element(symbol="W", atomic_number=74, mass=183.95093092 * unit.amu)
Re = Element(symbol="Re", atomic_number=75, mass=186.9557501 * unit.amu)
Os = Element(symbol="Os", atomic_number=76, mass=191.961477 * unit.amu)
Ir = Element(symbol="Ir", atomic_number=77, mass=192.9629216 * unit.amu)
Pt = Element(symbol="Pt", atomic_number=78, mass=194.9647917 * unit.amu)
Au = Element(symbol="Au", atomic_number=79, mass=196.96656879 * unit.amu)
Hg = Element(symbol="Hg", atomic_number=80, mass=201.9706434 * unit.amu)
Tl = Element(symbol="Tl", atomic_number=81, mass=204.9744278 * unit.amu)
Pb = Element(symbol="Pb", atomic_number=82, mass=207.9766525 * unit.amu)
Bi = Element(symbol="Bi", atomic_number=83, mass=208.9803991 * unit.amu)
Po = Element(symbol="Po", atomic_number=84, mass=208.9824308 * unit.amu)
At = Element(symbol="At", atomic_number=85, mass=209.9871479 * unit.amu)
Rn = Element(symbol="Rn", atomic_number=86, mass=222.0175782 * unit.amu)
Fr = Element(symbol="Fr", atomic_number=87, mass=223.019736 * unit.amu)
Ra = Element(symbol="Ra", atomic_number=88, mass=226.0254103 * unit.amu)
Ac = Element(symbol="Ac", atomic_number=89, mass=227.0277523 * unit.amu)
Th = Element(symbol="Th", atomic_number=90, mass=232.0380558 * unit.amu)
Pa = Element(symbol="Pa", atomic_number=91, mass=231.0358842 * unit.amu)
U = Element(symbol="U", atomic_number=92, mass=238.0507884 * unit.amu)
Np = Element(symbol="Np", atomic_number=93, mass=237.0481736 * unit.amu)
Pu = Element(symbol="Pu", atomic_number=94, mass=244.0642053 * unit.amu)
Am = Element(symbol="Am", atomic_number=95, mass=243.0613813 * unit.amu)
Cm = Element(symbol="Cm", atomic_number=96, mass=247.0703541 * unit.amu)
Bk = Element(symbol="Bk", atomic_number=97, mass=247.0703073 * unit.amu)
Cf = Element(symbol="Cf", atomic_number=98, mass=251.0795886 * unit.amu)
Es = Element(symbol="Es", atomic_number=99, mass=252.08298 * unit.amu)
Fm = Element(symbol="Fm", atomic_number=100, mass=257.0951061 * unit.amu)
Md = Element(symbol="Md", atomic_number=101, mass=258.0984315 * unit.amu)
No = Element(symbol="No", atomic_number=102, mass=259.10103 * unit.amu)
Lr = Element(symbol="Lr", atomic_number=103, mass=266.11983 * unit.amu)
Rf = Element(symbol="Rf", atomic_number=104, mass=267.12179 * unit.amu)
Db = Element(symbol="Db", atomic_number=105, mass=268.12567 * unit.amu)
Sg = Element(symbol="Sg", atomic_number=106, mass=271.13393 * unit.amu)
Bh = Element(symbol="Bh", atomic_number=107, mass=270.13336 * unit.amu)
Hs = Element(symbol="Hs", atomic_number=108, mass=269.13375 * unit.amu)
Mt = Element(symbol="Mt", atomic_number=109, mass=278.15631 * unit.amu)
Ds = Element(symbol="Ds", atomic_number=110, mass=281.16451 * unit.amu)
Rg = Element(symbol="Rg", atomic_number=111, mass=282.16912 * unit.amu)
Cn = Element(symbol="Cn", atomic_number=112, mass=285.17712 * unit.amu)
Nh = Element(symbol="Nh", atomic_number=113, mass=286.18221 * unit.amu)
Fl = Element(symbol="Fl", atomic_number=114, mass=289.19042 * unit.amu)
Mc = Element(symbol="Mc", atomic_number=115, mass=289.19363 * unit.amu)
Lv = Element(symbol="Lv", atomic_number=116, mass=293.20449 * unit.amu)
Ts = Element(symbol="Ts", atomic_number=117, mass=294.21046 * unit.amu)
```

Execution:

```
>>> Element(symbol="H") is Element.atomic_numbers[1]
True
```

**Comment by lilyminium** [comment]
> Could you elaborate a little bit here? I agree that in general there should not be an uncountably infinite number of elements packages out there, but the purpose of packages like this one for units is to standardize the solution within our stack. If we wanted to make an elements solution here, we could.

Sorry, I was being self-deprecating about my suggestion of making *yet more* elements classes in a new package (i.e. adding openff.Element, vs. openmm.Element, mendeleev.Element, ele.Element, ...)

> from only knowing an atom's atomic number

This is extremely attractive. My one annoyance would be that you would have to look up the mass every time, instead of storing just the element and pointing the .atomic_number, .mass etc. properties to the element. In terms of efficiency, in a normal `__dict__`-based structure I think the access overhead would be negligibly lower (and `__slot__` based negligibly lower than that) for `openff.elements.masses[atom.atomic_number]` vs. `atom.element.mass`. However, the set-up cost of creating classes etc. compared to dictionaries probably goes the other way.

> I'm curious what sort of technical roadblocks you ran into

It's not so much I ran into a roadblock as I wasted my Sunday making https://github.com/lilyminium/elementable, starting out with the idea of a generic lightweight elements package and ending up with... well, something. I'm not sure how lightweight it really ended up being. The idea is that `elementable.Elementable` is a metaclass that generates the Element class for you from a JSON file, so you can choose:

* whether you want units or not, and which ones (I've tested openff.units, openmm.units, and unyt)
* if you want to subclass anything (I've tested Pydantic)
* which attributes / data you want to support on each element (e.g. only choosing the atomic_number and mass instead of everything)
* the actual values of the data (e.g. masses to x decimal place)

> > I've realized there needs to be a more long-term solution than the proliferation of individually shipped elements classes.

^^^ Elementable came from this above feeling, which came from feeling like you and I were both trying to do very similar things at the same time, but necessarily different because of different project needs, and reading the issue thread where even OpenMM element masses differ from mendeleev masses. It probably isn't the right long-term solution, but it was a fun side-project.

>  The only non-negotiable to me is that the "just use some simple dictionaries" code path can be accessible without much overhead

`elementable.Elementable` returns a container that has a `.registry` attached, you could access those with `container.registry.atomic_numbers[1]` etc.

If you wanted to poke it or trial it as an elements solution for `openff.units`, I did stick it on conda-forge, but I've not done a super large amount of testing myself and it's only about a day old. There are a few assumptions in it based on what I wanted from elements at the time, like the returned elements container is a namedtuple because that allows indexing like `container[1]`. The default base class is also a namedtuple because those are immutable, fast, and serializable.

```python
>>> from elementable import Elementable
>>> from openff.units import unit
>>> elements = Elementable(units={"mass": unit.amu})
>>> elements.H
Element(name='hydrogen', symbol='H', atomic_number=1, mass=<Quantity(1.00782503, 'unified_atomic_mass_unit')>, period=1, group=1, covalent_radius=0.31)
>>> elements.H.mass
<Quantity(1.00782503, 'unified_atomic_mass_unit')>
>>> elements[1]
Element(name='hydrogen', symbol='H', atomic_number=1, mass=<Quantity(1.00782503, 'unified_atomic_mass_unit')>, period=1, group=1, covalent_radius=0.31)
>>> elements[1] is elements.registry.name['hydrogen']
True
```

Happy lunar new year('s eve)!

**Review by j-wags — APPROVED** [review]
Sweet. This looks great. 

For future people who look and ask why we chose to do this: 
* `pint` doesn't have periodic table info
* The alternative is either bringing in a different externally-maintained periodic table package with slightly different masses and justifying the change, or continuing to pull in hundreds of MB of the openmm+CUDA packages just to use the periodic table. 
* This will be easy to swap out once we decide which masses we "want" to use

**Comment by mattwthompson** [comment]
Thanks @j-wags and @lilyminium for the review and thoughtful comments!

This should land in v0.1.5.

**Pull request merged**
